export const CHAINLINK_ID = "chainlink"
export const ETHEREUM_ID = "ethereum"
export const ZEROX_ID = "0x"
export const AAVE_ID = "aave"
export const ENS_ID = "ens"
export const OPEN_ZEPPELIN_ID = "openzeppelin"
export const TABLELAND_ID = "tableland"
export const UNISWAP_ID = "uniswap"
export const COMPOUND_ID = "compound"
export const ARBITRUM_ID = "arbitrum"
export const METIS_ID = "metis"
export const IMMUTABLE_ID = "immutable"
export const THEGRAPH_ID = "the-graph"
export const ARTELA_ID = "artela"
export const GMX_ID = "gmx"
export const FUSE_ID = "fuse"
export const PUSH_PROTOCOL_ID = "push"
export const AZUKI_ID = "azuki"
export const RONIN_ID = "ronin"
export const BERACHAIN_ID = "berachain"
export const JUICE_BOX_DAO_ID = "juice-box"



