export const CHAINLINK_ID = "chainlink"
export const ETHEREUM_ID = "ethereum"
export const ZEROX_ID = "0x"
export const AAVE_ID = "aave"
export const ENS_ID = "ens"
export const OPEN_ZEPPELIN_ID = "openzeppelin"
export const TABLELAND_ID = "tableland"
export const UNISWAP_ID = "uniswap"
